local RavenCreekFarm = {
    doorKeys = {
        name = "Raven Creek Farm Key",
        doors = {
            { x = 6390, y = 16220, z = 0, },
            { x = 6387, y = 16221, z = -1, },
        },
    },
    map = { name = "DWAP_RCF_StashMap1", },
    generators = {
        {
            controls = { sprite = "industry_02_67", x = 6376, y = 16208, z = -1, },
            fakeGenerators = {
                { x = 6385, y = 16218, z = -2, },
            },
            solar = {
                powerbank = { sprite = "dwap_tiles_01_0", x = 6377, y = 16208, z = -1 },
                panels = {
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 6385,
                        y = 16222,
                        z = 1,
                        pb = 1,
                        spawn = false,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 6386,
                        y = 16222,
                        z = 1,
                        pb = 1,
                        spawn = false,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 6387,
                        y = 16222,
                        z = 1,
                        pb = 1,
                        spawn = false,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 6388,
                        y = 16222,
                        z = 1,
                        pb = 1,
                        spawn = false,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 6389,
                        y = 16222,
                        z = 1,
                        pb = 1,
                        spawn = false,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 6390,
                        y = 16222,
                        z = 1,
                        pb = 1,
                        spawn = false,
                    },
                    {
                        type = "panel",
                        isSpecial = true,
                        sprite = "solarmod_tileset_01_10",
                        x = 6391,
                        y = 16222,
                        z = 1,
                        pb = 1,
                        spawn = false,
                    },
                },
            },
        },
    },
    waterTanks = {
        { sprite = "dwap_tiles_01_9", x = 6374, y = 16211, z = -1, sourceType="generator", source = 1, },
    },
    waterFixtures = {
        { sprite = "fixtures_sinks_01_16", x = 6373, y = 16226, z = -1, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_24", x = 6378, y = 16212, z = -1, sourceType="tank", source = 1, },
        { sprite = "location_shop_zippee_01_57", x = 6378, y = 16222, z = -1, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_34", x = 6382, y = 16216, z = -1, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_3", x = 6386, y = 16217, z = -1, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_12", x = 6387, y = 16207, z = -1, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_28", x = 6387, y = 16217, z = -1, sourceType="tank", source = 1, },

        { sprite = "fixtures_bathroom_01_26", x = 6385, y = 16215, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_21", x = 6385, y = 16216, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_21", x = 6385, y = 16217, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_27", x = 6386, y = 16215, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_0", x = 6387, y = 16215, z = 0, sourceType="tank", source = 1, },
        { sprite = "appliances_laundry_01_5", x = 6388, y = 16212, z = 0, sourceType="tank", source = 1, },
        { sprite = "appliances_laundry_01_5", x = 6388, y = 16213, z = 0, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_22", x = 6394, y = 16212, z = 0, sourceType="tank", source = 1, },

        { sprite = "fixtures_bathroom_01_1", x = 6392, y = 16212, z = 1, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_26", x = 6392, y = 16214, z = 1, sourceType="tank", source = 1, },
        { sprite = "fixtures_bathroom_01_27", x = 6393, y = 16214, z = 1, sourceType="tank", source = 1, },
        { sprite = "fixtures_sinks_01_29", x = 6395, y = 16213, z = 1, sourceType="tank", source = 1, },
    },
    objectSpawns = {
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_01_41", x = 6381, y = 16223, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_01_41", x = 6383, y = 16223, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_01_61", x = 6386, y = 16221, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_01_61", x = 6388, y = 16221, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_01_41", x = 6393, y = 16223, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_01_41", x = 6398, y = 16223, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_01_40", x = 6400, y = 16221, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_01_40", x = 6400, y = 16219, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_01_40", x = 6400, y = 16215, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_exterior_house_01_40", x = 6400, y = 16213, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_02_57", x = 6389, y = 16212, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_02_57", x = 6383, y = 16212, z = 0, },
        { barricade = "woodhalf", enabled = "Barricade", target="walls_interior_house_02_57", x = 6381, y = 16212, z = 0, },
    },
    loot = {
        -- basement
        -- armory
        {
            type = 'container',
            coords = {x=6384,y=16219,z=-1},
            dist = {"ArmyStorageGuns","ArmyStorageAmmunition","FirearmWeapons_Late"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=6384,y=16220,z=-1},
            dist = { "GunStoreKnives", "PawnShopKnives",  },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=6384,y=16221,z=-1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=6384,y=16222,z=-1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=6384,y=16223,z=-1},
            dist = {"ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=6384,y=16224,z=-1},
            dist = {"HuntingLockers", "RangerTools", "CrateFishing", "FishermanTools"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FishLevel",
        },
        {
            type = 'container',
            coords = {x=6384,y=16225,z=-1},
            dist = {"ArmyStorageElectronics", "ToolFactoryIngots" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=6384,y=16226,z=-1},
            dist = {"ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=6384,y=16227,z=-1},
            dist = {"CrateSheetMetal","CrateLumber" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=6384,y=16228,z=-1},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=6387,y=16222,z=-1},
            sandboxEnable = 'Loot',
            special = "essentials",
        },
        {
            type = 'container',
            coords = {x=6387,y=16223,z=-1},
            dist = { "CarSupplyTools", "GasStorageMechanics",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=6387,y=16224,z=-1},
            dist = {"CampingStoreTools", "ArmyHangarTools", "CarSupplyTools", "BurglarTools", "CarpenterTools", "BarnTools", "GarageTools","GigamartTools", "JanitorTools", "LoggingFactoryTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=6387,y=16225,z=-1},
            dist = {"GasStoreEmergency", "StoreCounterTobacco", "CandyStoreSnacks"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6387,y=16226,z=-1},
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = {9,12} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=6387,y=16227,z=-1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy", "RandomFiller"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=6387,y=16228,z=-1},
            items = {
                { name = 'Base.Fertilizer', chance = 1, count = {8,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=6387,y=16229,z=-1},
            dist = {"ArtStorePottery",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- infirmary
        {
            type = 'container',
            coords = {x=6383,y=16211,z=-1},
            dist = {"LaboratoryLockers", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=6383,y=16210,z=-1},
            dist = {"MorgueTools", "ArmyStorageMedical", "ArmyBunkerMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=6383,y=16209,z=-1},
            dist = {"MedicalClinicDrugs" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=6383,y=16209,z=-0.5},
            dist = {"MedicalCabinet" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=6383,y=16207,z=-1},
            dist = {"MedicalCabinet", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=6387,y=16210,z=-1},
            dist = {"ArmyStorageMedical", "ArmyBunkerMedical" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        {
            type = 'container',
            coords = {x=6387,y=16211,z=-1},
            dist = {"SafehouseMedical_Late", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        -- study
        {
            type = 'container',
            coords = {x=6382,y=16211,z=-1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks1",
        },
        {
            type = 'container',
            coords = {x=6381,y=16211,z=-1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillbooks2",
        },
        {
            type = 'container',
            coords = {x=6378,y=16210,z=-1},
            dist = {"CrateLiquor", "LiquorStoreWhiskey"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6378,y=16209,z=-1},
            dist = {"CrateLiquor", "DishCabinetVIPLounge"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6380,y=16207,z=-1},
            items = {
                { name = 'Base.Firewood', chance = 1, count = {10,10} },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=6382,y=16207,z=-1},
            sandboxEnable = 'Loot_EnableBooks',
            special = "skillmags",
        },
        {
            type = 'container',
            coords = {x=6378,y=16208,z=-1},
            sandboxEnable = 'Loot_EnableMaps',
            special = "maps",
        },
        -- west storage
        {
            type = 'container',
            coords = {x=6375,y=16216,z=-1},
            dist = {"CrateTools", "GarageTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=6375,y=16217,z=-1},
            dist = {"BurglarTools", "CarpenterTools", "BarnTools" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=6377,y=16214,z=-1},
            dist = {"CampingStoreTools", "ArmyHangarTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=6374,y=16214,z=-1},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=6373,y=16214,z=-1},
            dist = {"GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=6373,y=16215,z=-1},
            dist = {"SewingStoreTools","SewingStoreFabric", "CrateLeather"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_TailorLevel",
        },
        {
            type = 'container',
            coords = {x=6373,y=16216,z=-1},
            dist = {"GigamartBreakfast","GigamartCandy","Homesteading","CrateLiquor",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6373,y=16217,z=-1},
            dist = {"ArmyStorageAmmunition", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=6377,y=16215,z=-1},
            items = {
                { name = 'Base.Shoes_ArmyBoots', chance = 1, count = {7,13} },
                { name = 'Base.Shoes_ArmyBootsDesert', chance = 1, count = {3,7} },
            },
        },
        {
            type = 'container',
            coords = {x=6377,y=16216,z=-1},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=6377,y=16217,z=-1},
            dist = {"SafehouseArmor",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=6377,y=16218,z=-1},
            dist = {"SafehouseArmor",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- workshop
        {
            type = 'container',
            coords = {x=6382,y=16218,z=-1},
            items = {
                { name = 'Base.NailsBox', },
                { name = 'Base.ScrewsBox', },
            },
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=6382,y=16217,z=-1},
            dist = {"ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=6379,y=16214,z=-1},
            dist = { "CrateTools", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        {
            type = 'container',
            coords = {x=6382,y=16215,z=-1},
            dist = { "ToolFactoryHandles", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_ToolsLevel",
        },
        -- bar / game room
        {
            type = 'container',
            coords = {x=6378,y=16223,z=-1},
            dist = {"LiquorStoreBeer","LiquorStoreBeerFancy","LiquorStoreWine"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6378,y=16224,z=-1},
            dist = {"CrateLiquor", "LiquorStoreBrandy"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6378,y=16225,z=-1},
            dist = {"CrateLiquor", "LiquorStoreMix"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- kitchen
        {
            type = 'container',
            coords = {x=6377,y=16223,z=-1},
            dist = {"TheatreSnacks"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6377,y=16224,z=-1},
            dist = {"BarCounterMisc"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6377,y=16226,z=-1},
            dist = {"CrateButter"},
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6376,y=16229,z=-1},
            dist = {"SushiKitchenFreezer"},
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6375,y=16229,z=-1},
            dist = {"FreezerIceCream", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6373,y=16228,z=-1},
            dist = {"SpiffosKitchenFridge", "SpiffosKitchenFreezer"},
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6373,y=16227,z=-1},
            dist = {"GigamartBreakfast"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6373,y=16227,z=-0.5},
            dist = {"StoreKitchenPotatoes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6373,y=16225,z=-1},
            dist = {"GigamartDryGoods", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6373,y=16225,z=-0.5},
            dist = {"CrateTortillaChips", "KitchenDryFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6373,y=16224,z=-1},
            dist = {"GigamartBakingMisc", "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6373,y=16224,z=-0.5},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6376,y=16219,z=-1},
            dist = {"KitchenBook","GigamartSpices",},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
    },
}

return RavenCreekFarm
