local RavenCreekFarm = require "DWAP_RavenCreek_Farm/configs/RCF"
print("DWAP Raven Creek Farm extraLoot.lua loaded")
local extraLoot = {
    -- basement kitchen
        {
            type = 'container',
            coords = {x=6377,y=16222,z=-1},
            dist = {"TheatrePopcorn"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6377,y=16225,z=-1},
            dist = {"CafeKitchenCoffee"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6373,y=16229,z=-1},
            dist = {"PizzaKitchenFreezer", "PizzaKitchenFridge"},
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6373,y=16222,z=-1},
            dist = {"FridgeFarmStorage", "FridgeGeneric", "SushiKitchenFridge"},
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6373,y=16226,z=-1},
            dist = {"CrateSodaBottles", "CrateSodaCans"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6373,y=16226,z=-0.5},
            dist = {"ArenaKitchenSauce"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- basement armory
        {
            type = 'container',
            coords = {x=6384,y=16229,z=-1},
            special = "gunlocker",
            level = "Loot_GunLevel",
        },
        -- basement workshop
        {
            type = 'container',
            coords = {x=6382,y=16214,z=-1},
            dist = {"CrateLumber", "CrateSheetMetal","ArtStorePottery","CrateMasonry" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=6373,y=16218,z=-1},
            dist = {"CrateLumber", "CrateSheetMetal","ArtStorePottery","CrateMasonry" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
-- farmhouse
        -- office/study room
        {
            type = 'container',
            coords = {x=6380,y=16213,z=0},
            dist = {"CrateLiquor", "DishCabinetVIPLounge", "BookstoreBiography", "BookstoreBusiness", "BookstoreChilds", "BookstoreComputer", "BookstoreCrimeFiction"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=6380,y=16214,z=0},
            dist = {"CrateVHSTapes"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=6380,y=16215,z=0},
            dist = {"CrateLiquor", "DishCabinetVIPLounge", "MusicStoreCDs", },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        -- bathroom
        {
            type = 'container',
            coords = {x=6385,y=16216,z=0},
            dist = {"CrateToiletPaper", "CrateLinens", "GasStoreToiletries"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=6385,y=16217,z=0},
            dist = {"SafehouseMedical_Late", "BathroomCounter", },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_MedLevel",
        },
        -- storage room
        {
            type = 'container',
            coords = {x=6386,y=16212,z=0},
            dist = {"WireFactoryBarbed", "CrateLongStick", "WireFactoryBasic"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=6387,y=16212,z=0},
            dist = {"CrateLumber", "CrateSheetMetal", "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=6387,y=16213,z=0},
            dist = {"RailYardSpikes", "WeldingWorkshopMetal","ToolFactoryIngots"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        {
            type = 'container',
            coords = {x=6387,y=16214,z=0},
            dist = {"RadioFactoryComponents", "CrateElectronics", "ArmyStorageElectronics"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_BuildMatsLevel",
        },
        -- laundry room
        {
            type = 'container',
            coords = {x=6391,y=16212,z=0},
            dist = {"ArmyStorageOutfit", "DrugLabOutfit", "RandomFiller"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=6391,y=16213,z=0},
            dist = {"LockerArmyBedroom", "LockerArmyBedroomHome", "RandomFiller"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=6391,y=16214,z=0},
            dist = {"ArmySurplusOutfit", "CrateBootsArmy", "RandomFiller"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        -- kitchen
        {
            type = 'container',
            coords = {x=6392,y=16212,z=0},
            special = "kitchentools",
        },
        {
            type = 'container',
            coords = {x=6392,y=16215,z=0},
            dist = {"CafeKitchenSupplies", "CafeKitchenTea", "CrateSodaBottles"},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6393,y=16212,z=0},
            dist = {"GigamartBakingMisc", "CrateFlour", "CrateOilVegetable" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6394,y=16212,z=0},
            dist = {"ButcherSpices","GigamartSpices","GroceryBagGourmet","CrateCannedFood", "KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6395,y=16212,z=0},
            dist = {"KitchenCannedFood"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        { --fridge
            type = 'container',
            coords = {x=6396,y=16212,z=0},
            dist = {"FreezerIceCream", },
            distIncludeJunk = false,
            randUntilFull = true,
            frozen = true,
            level = "Loot_FoodLevel",
        },
        { -- fridge
            type = 'container',
            coords = {x=6397,y=16212,z=0},
            dist = {"SafehouseFridge"},
            frozen = true,
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6398,y=16212,z=0},
            dist = {"GigamartDryGoods", "GigamartBreakfast"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        -- center island
        {
            type = 'container',
            coords = {x=6394,y=16214,z=0},
            dist = {"GigamartDryGoods", "CrateCannedFood", "KitchenCannedFood" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6394,y=16215,z=0},
            dist = {"GigamartDryGoods", "CafeKitchenCoffee"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6395,y=16214,z=0},
            dist = {"CrateTortillaChips"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6395,y=16215,z=0},
            dist = {"CandyStoreSnacks","StoreShelfDrinks",},
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6396,y=16214,z=0},
            dist = { "ArmyStorageAmmunition", "GunStoreKnives", "DerelictHouseCrime" },
            distIncludeJunk = true,
            randUntilFull = true,
            level = "Loot_GunLevel",
        },
        {
            type = 'container',
            coords = {x=6396,y=16215,z=0},
            dist = { "CrateLiquor", "LiquorStoreWhiskey" },
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_FoodLevel",
        },
        {
            type = 'container',
            coords = {x=6397,y=16214,z=0},
            items = {
                { name = 'Base.Fertilizer', chance = 1, count = { 8, 10 } },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        {
            type = 'container',
            coords = {x=6397,y=16215,z=0},
            items = {
                { name = 'Base.AnimalFeedBag', chance = 1, count = { 9, 12 } },
            },
            randUntilFull = true,
            level = "Loot_FarmLevel",
        },
        -- dining
        {
            type = 'container',
            coords = {x=6392,y=16216,z=0},
            dist = {"MovieRentalShelves"},
            distIncludeJunk = false,
            randUntilFull = true,
            level = "Loot_MediaLevel",
        },
        {
            type = 'container',
            coords = {x=6392,y=16217,z=0},
            items = {
                { name = 'Base.Bag_ProtectiveCaseBulkyHazard', },
                { name = 'Base.Hat_NBCmask', },
                { name = 'Base.Glasses_SafetyGoggles', },
                { name = 'Base.Hat_BuildersRespirator', },
                { name = 'Base.HazmatSuit', },
                { name = 'Base.RespiratorFilters', },
                { name = 'Base.Hat_GasMask', },
                { name = 'Base.GasmaskFilter', },
            },
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
        {
            type = 'container',
            coords = {x=6392,y=16218,z=0},
            items = {
                { name = 'Base.Oxygen_Tank', },
            },
            randUntilFull = true,
            level = "Loot_LockersLevel",
        },
}

if RavenCreekFarm and RavenCreekFarm.loot then
    for i = 1, #extraLoot do
        table.insert(RavenCreekFarm.loot, extraLoot[i])
    end
end

return RavenCreekFarm
